"""ledger blocks timestamp ms

Revision ID: 285ad7666f50
Revises: 47217ec0889a
Create Date: 2026-09-25 05:55:23.562963

"""
from alembic import op
import sqlalchemy as sa


revision = '285ad7666f50'
down_revision = '47217ec0889a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_ms', sa.BigInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_blocks', schema=None) as batch_op:
        batch_op.drop_column('timestamp_ms')

    # ### end Alembic commands ###
