"""blockchain events outbox payload

Revision ID: 47217ec0889a
Revises: e7e54d7c55cc
Create Date: 2026-09-25 05:52:30.970918

"""
from alembic import op
import sqlalchemy as sa


revision = '47217ec0889a'
down_revision = 'e7e54d7c55cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blockchain_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blockchain_events', schema=None) as batch_op:
        batch_op.drop_column('data_json')

    # ### end Alembic commands ###
