"""care platform baseline v4.1

Revision ID: e7e54d7c55cc
Revises: 
Create Date: 2026-09-25 04:27:33.248184

"""
from alembic import op
import sqlalchemy as sa


revision = 'e7e54d7c55cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('block_ref', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_logs'))
    )
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.create_index('ix_access_logs_actor_action_time', ['actor_id', 'action', 'created_at'], unique=False)
        batch_op.create_index('ix_access_logs_resource', ['resource_type', 'resource_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('block_ref', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_event_time', ['event_type', 'created_at'], unique=False)

    op.create_table('federated_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_model', sa.String(length=64), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('epsilon', sa.Float(), nullable=True),
    sa.Column('cumulative_epsilon', sa.Float(), nullable=True),
    sa.Column('model_hash', sa.String(length=64), nullable=True),
    sa.Column('block_index', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_federated_jobs'))
    )
    with op.batch_alter_table('federated_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_federated_jobs_status_round', ['status', 'round'], unique=False)

    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('node_address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hospitals')),
    sa.UniqueConstraint('code', name=op.f('uq_hospitals_code'))
    )
    op.create_table('ledger_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_blocks')),
    sa.UniqueConstraint('block_hash', name=op.f('uq_ledger_blocks_block_hash')),
    sa.UniqueConstraint('block_index', name=op.f('uq_ledger_blocks_block_index'))
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('artifact_reference', sa.String(length=512), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('model_id', 'version', name='uq_model_versions_model_version')
    )
    op.create_table('blockchain_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_event_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('tx_reference', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['ledger_blocks.id'], name=op.f('fk_blockchain_events_block_id_ledger_blocks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blockchain_events'))
    )
    with op.batch_alter_table('blockchain_events', schema=None) as batch_op:
        batch_op.create_index('ix_blockchain_events_state', ['state'], unique=False)

    op.create_table('model_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('federated_job_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('update_hash', sa.String(length=64), nullable=True),
    sa.Column('samples_count', sa.Integer(), nullable=True),
    sa.Column('clip_norm', sa.Float(), nullable=True),
    sa.Column('noise_sigma', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['federated_job_id'], ['federated_jobs.id'], name=op.f('fk_model_updates_federated_job_id_federated_jobs')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_model_updates_hospital_id_hospitals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_updates'))
    )
    with op.batch_alter_table('model_updates', schema=None) as batch_op:
        batch_op.create_index('ix_model_updates_job_status', ['federated_job_id', 'status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('PATIENT', 'DOCTOR', 'HOSPITAL_ADMIN', 'SYSTEM_ADMIN', 'REGULATOR')", name=op.f('ck_users_valid_role')),
    sa.CheckConstraint("status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'DISABLED', 'DELETED')", name=op.f('ck_users_valid_status')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_users_hospital_id_hospitals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_hospital', ['hospital_id'], unique=False)
        batch_op.create_index('ix_users_role_status', ['role', 'status'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_type', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('jti', name=op.f('uq_auth_sessions_jti'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_auth_sessions_user_type', ['user_id', 'token_type'], unique=False)

    op.create_table('care_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE','ENDED','CANCELLED')", name=op.f('ck_care_relationships_valid_status')),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('fk_care_relationships_doctor_id_users')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_care_relationships_hospital_id_hospitals')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_care_relationships_patient_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_care_relationships'))
    )
    with op.batch_alter_table('care_relationships', schema=None) as batch_op:
        batch_op.create_index('ix_care_relationships_patient_doctor_status', ['patient_id', 'doctor_id', 'status'], unique=False)

    op.create_table('consent_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','APPROVED','REJECTED','CANCELLED')", name=op.f('ck_consent_requests_valid_status')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_consent_requests_patient_id_users')),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_consent_requests_requester_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_requests'))
    )
    with op.batch_alter_table('consent_requests', schema=None) as batch_op:
        batch_op.create_index('ix_consent_requests_patient_status', ['patient_id', 'status'], unique=False)

    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('specialty', sa.String(length=128), nullable=True),
    sa.Column('license_number', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_doctor_profiles_hospital_id_hospitals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_doctor_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_doctor_profiles_user_id'))
    )
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'ARCHIVED', 'DELETED')", name=op.f('ck_medical_records_valid_status')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_medical_records_patient_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_records'))
    )
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index('ix_medical_records_patient_status_time', ['patient_id', 'status', 'created_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_read_time', ['user_id', 'read', 'created_at'], unique=False)

    op.create_table('patient_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pseudo_id', sa.String(length=32), nullable=False),
    sa.Column('synthetic_attributes', sa.JSON(), nullable=True),
    sa.Column('research_consent_cache', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_patient_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_profiles')),
    sa.UniqueConstraint('pseudo_id', name=op.f('uq_patient_profiles_pseudo_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_patient_profiles_user_id'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('permission_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('audit_ref', sa.String(length=64), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("NOT (status = 'ACTIVE' AND revoked_at IS NOT NULL)", name=op.f('ck_permissions_active_implies_not_revoked')),
    sa.CheckConstraint("status IN ('PENDING', 'ACTIVE', 'REJECTED', 'EXPIRED', 'REVOKED', 'CANCELLED')", name=op.f('ck_permissions_valid_status')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_permissions_patient_id_users')),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_permissions_recipient_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index('ix_permissions_authz', ['patient_id', 'recipient_user_id', 'resource_type', 'resource_id', 'status'], unique=False)

    op.create_table('research_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('allowed_organizations', sa.JSON(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'REVOKED', 'EXPIRED')", name=op.f('ck_research_consents_valid_status')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_research_consents_patient_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_consents'))
    )
    with op.batch_alter_table('research_consents', schema=None) as batch_op:
        batch_op.create_index('ix_research_consents_patient_status', ['patient_id', 'status'], unique=False)

    op.create_table('medical_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('storage_reference', sa.String(length=512), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], name=op.f('fk_medical_files_record_id_medical_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_files'))
    )
    with op.batch_alter_table('medical_files', schema=None) as batch_op:
        batch_op.create_index('ix_medical_files_checksum', ['checksum'], unique=False)

    op.create_table('permission_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(target_user_id IS NOT NULL) <> (organization_id IS NOT NULL)', name=op.f('ck_permission_targets_valid_target')),
    sa.ForeignKeyConstraint(['organization_id'], ['hospitals.id'], name=op.f('fk_permission_targets_organization_id_hospitals')),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_permission_targets_permission_id_permissions')),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_permission_targets_target_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_targets'))
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('medication', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=128), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('fk_prescriptions_doctor_id_users')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_prescriptions_patient_id_users')),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], name=op.f('fk_prescriptions_record_id_medical_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions'))
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['medical_files.id'], name=op.f('fk_reports_file_id_medical_files')),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], name=op.f('fk_reports_record_id_medical_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_reports_record_status', ['record_id', 'status'], unique=False)

    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('result_reference', sa.String(length=512), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('failure_category', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED','PROCESSING','COMPLETED','FAILED','TIMEOUT','CANCELLED')", name=op.f('ck_ai_analyses_valid_status')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_ai_analyses_report_id_reports')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_ai_analyses_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses'))
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_ai_analyses_report_status', ['report_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_analyses_report_status')

    op.drop_table('ai_analyses')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_record_status')

    op.drop_table('reports')
    op.drop_table('prescriptions')
    op.drop_table('permission_targets')
    with op.batch_alter_table('medical_files', schema=None) as batch_op:
        batch_op.drop_index('ix_medical_files_checksum')

    op.drop_table('medical_files')
    with op.batch_alter_table('research_consents', schema=None) as batch_op:
        batch_op.drop_index('ix_research_consents_patient_status')

    op.drop_table('research_consents')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index('ix_permissions_authz')

    op.drop_table('permissions')
    op.drop_table('patient_profiles')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read_time')

    op.drop_table('notifications')
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index('ix_medical_records_patient_status_time')

    op.drop_table('medical_records')
    op.drop_table('doctor_profiles')
    with op.batch_alter_table('consent_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_consent_requests_patient_status')

    op.drop_table('consent_requests')
    with op.batch_alter_table('care_relationships', schema=None) as batch_op:
        batch_op.drop_index('ix_care_relationships_patient_doctor_status')

    op.drop_table('care_relationships')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_sessions_user_type')

    op.drop_table('auth_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role_status')
        batch_op.drop_index('ix_users_hospital')

    op.drop_table('users')
    with op.batch_alter_table('model_updates', schema=None) as batch_op:
        batch_op.drop_index('ix_model_updates_job_status')

    op.drop_table('model_updates')
    with op.batch_alter_table('blockchain_events', schema=None) as batch_op:
        batch_op.drop_index('ix_blockchain_events_state')

    op.drop_table('blockchain_events')
    op.drop_table('model_versions')
    op.drop_table('ledger_blocks')
    op.drop_table('hospitals')
    with op.batch_alter_table('federated_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_federated_jobs_status_round')

    op.drop_table('federated_jobs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_event_time')

    op.drop_table('audit_logs')
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_access_logs_resource')
        batch_op.drop_index('ix_access_logs_actor_action_time')

    op.drop_table('access_logs')
    # ### end Alembic commands ###
